version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/wiki-frontend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"

  - package-ecosystem: "nuget"
    directory: "/wiki-backend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"

  - package-ecosystem: "docker"
    directories:
      - "/wiki-frontend"
      - "/wiki-backend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
    labels:
      - "ci"
