// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wiki_backend.DatabaseServices;

#nullable disable

namespace wiki_backend.Migrations
{
    [DbContext(typeof(WikiDbContext))]
    [Migration("20240131103618_BogusParagraphs")]
    partial class BogusParagraphs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("wiki_backend.Models.Paragraph", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IntroductionParagraph")
                        .HasColumnType("bit");

                    b.Property<string>("ParagraphImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParagraphImageText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WikiPageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WikiPageId");

                    b.ToTable("Paragraphs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Debitis est quia quisquam ea. Et dolorem numquam dignissimos. Consequatur ea similique qui excepturi est. Aliquam doloribus quod ex nulla omnis eos voluptas qui possimus.\n\nEum aut dolore est eveniet ducimus. Voluptate velit est quia. Recusandae magnam ullam in perferendis est ea ipsa doloremque et. Assumenda magni aspernatur expedita amet rerum ipsum.\n\nEt suscipit ut ipsum quisquam assumenda. Et et iste occaecati nobis ipsam neque dicta. Accusantium maxime at sed sit cum illo nemo magni incidunt. Laboriosam beatae porro eos provident odit tempore eveniet fuga labore.\n\nAlias cumque sint. Non quasi impedit commodi totam quos. Voluptatum quos ea architecto delectus vero totam reiciendis.\n\nNecessitatibus culpa sapiente ducimus molestiae explicabo quasi voluptas. Quam corrupti soluta enim ut sed placeat velit et est. Exercitationem qui sed delectus fugiat commodi. Et rerum qui et omnis est. Eos fugiat cupiditate tenetur vel repudiandae quidem. Ad labore officiis aut voluptas illo et reprehenderit dolor.",
                            IntroductionParagraph = false,
                            Title = "Example Paragraph 1",
                            WikiPageId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Est ut distinctio sit vitae molestias vel recusandae. Commodi eum repudiandae numquam excepturi harum non vitae. Magnam dolorem velit eos maiores qui mollitia.\n\nVoluptas dolor sit quisquam laudantium eveniet accusantium esse cum. Blanditiis maxime quae neque. Molestiae est aut recusandae. At voluptate et commodi omnis eos omnis.\n\nSed magnam est debitis consequuntur qui laudantium. Voluptatem vero dolor at quisquam molestias et libero et expedita. Similique dolorem et eos doloribus repellendus quibusdam recusandae. Ipsa quisquam officiis aut cumque sed velit debitis vel non.\n\nIusto deserunt facere ea consequuntur omnis nostrum tempore fuga aut. Facere aut necessitatibus. Fugit officia amet et qui quibusdam. Quidem omnis autem possimus qui voluptas iure aut aliquid.\n\nEst doloremque vero laudantium asperiores laborum est deleniti consequatur doloribus. Est soluta nihil ullam animi aliquid incidunt nisi dolorem aut. Et quo magni quia consequatur fugit quo repellendus. Officiis quo mollitia ab dolorem. Qui delectus voluptatem blanditiis.",
                            IntroductionParagraph = false,
                            Title = "Example Paragraph 2",
                            WikiPageId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "Id est excepturi. Ipsam et omnis quae ipsa dolorum architecto quia qui corporis. Amet accusamus qui qui eum perspiciatis. Necessitatibus occaecati adipisci ut nulla repellat quia.\n\nSoluta eum deserunt. Voluptate cupiditate quo. Ipsum est officia ipsa provident debitis ut enim.\n\nTempore cum a ipsa rem. Accusamus corrupti aliquid nesciunt occaecati officiis. Aut laudantium dolorem. Modi eius fugit autem nobis. Nobis distinctio officia voluptas facilis vitae et odio excepturi maxime.\n\nAut quasi perferendis vel aspernatur repellat ut repudiandae. Nam explicabo sint suscipit error earum facilis a cupiditate. Accusantium fugit quo voluptatibus quasi est magnam aut eius voluptatem. Voluptatibus quod doloremque quibusdam expedita facilis sed rerum rem omnis. Placeat non mollitia odio corrupti. Eum qui ipsam ipsa et ratione commodi.\n\nSed corporis voluptatum iusto qui dicta iusto debitis exercitationem sed. Sapiente voluptates facere in impedit. Aut enim magnam qui atque libero aliquam. Veritatis eligendi similique hic odit commodi qui cum voluptas alias.",
                            IntroductionParagraph = false,
                            Title = "Example Paragraph 3",
                            WikiPageId = 2
                        },
                        new
                        {
                            Id = 4,
                            Content = "Ipsam et cum rerum et. Aperiam cumque consequatur eveniet perferendis veritatis saepe expedita fugiat deleniti. Quisquam reprehenderit quae eos soluta explicabo corrupti provident.\n\nEt tenetur ullam labore eius. Facilis recusandae sint. Mollitia sed et libero. Quia omnis fuga eveniet exercitationem et ipsum ut praesentium hic. Ut nihil eveniet repellendus amet beatae dolorem cum voluptas aspernatur.\n\nRatione atque reprehenderit quia quia eum sit dolorem reprehenderit. Incidunt aut quis. Amet hic iusto sed pariatur fugiat sint consequuntur consectetur.\n\nOccaecati alias odio molestias aliquid veritatis quia iure. Sunt maiores ullam cum consequatur optio vero et. Qui vitae autem voluptas molestiae et ut non ipsam. Natus consequatur magnam eligendi et voluptatem qui aliquid ea. Consequatur et assumenda ad.\n\nAssumenda ratione aperiam odit voluptatem. Quam debitis quia dolore ut voluptate laborum dolorem sequi cum. Sed distinctio amet perferendis qui ea neque et. Omnis fuga culpa. Culpa rem dolores atque natus tenetur aut dignissimos sapiente. Omnis id ipsa rerum aspernatur maiores dolorem dolor consectetur.",
                            IntroductionParagraph = false,
                            Title = "Example Paragraph 4",
                            WikiPageId = 1
                        },
                        new
                        {
                            Id = 5,
                            Content = "Provident non deleniti perferendis ad natus quae sed odit quia. Laudantium maxime magni omnis iure fugit aliquam aliquam. Ut qui nam quis praesentium voluptas mollitia. Veritatis voluptate optio sed. Molestias modi est.\n\nDolores explicabo animi. Consequatur ut eos quod ad. Sint debitis quis vero dolor quia quo consequatur est impedit.\n\nQui autem quo at ipsam nobis quibusdam. Quia aliquid minus iste possimus recusandae id. Ad aspernatur corrupti dolorem autem aut beatae ut. Excepturi et rerum laudantium voluptas quas aliquid voluptatem odio vero. Nostrum nihil dolorem qui rem maxime commodi voluptatem consectetur commodi.\n\nOfficiis ab rerum vel ut rerum vitae. Facere quia aliquam. Necessitatibus in eveniet eius ut id. Id rem modi impedit hic odio natus.\n\nPariatur rerum quibusdam quam qui aut velit impedit exercitationem. Doloribus quo consequatur velit est. Sint autem beatae soluta veritatis placeat non vero velit dolorum. Hic atque sint vel minima veniam facere enim nihil.",
                            IntroductionParagraph = false,
                            Title = "Example Paragraph 5",
                            WikiPageId = 1
                        },
                        new
                        {
                            Id = 6,
                            Content = "Similique non quaerat natus. Quo odit nostrum modi eum. Est vero facere magni dolorum. Excepturi et totam officiis ullam corrupti quidem. Soluta sint et eos officia. Sapiente molestiae et eum ex ea.\n\nEos reprehenderit reprehenderit. Atque vel magnam sed nam aut aliquam. Quia est alias laudantium aut voluptas asperiores ut sit. Ipsa architecto vitae saepe ullam.\n\nOfficia quibusdam non tempore iure laborum dolor. Est voluptatem excepturi qui mollitia fuga voluptatum est. Earum nemo quis ratione facere porro explicabo velit molestiae. Eos harum consectetur ad facilis totam et ut. Et natus quibusdam cumque consequatur dolore hic. Natus exercitationem repellendus est eos itaque harum dolor aut.\n\nEst velit ad libero totam autem. Qui natus fuga alias facilis quod unde enim sunt totam. Et tenetur excepturi reiciendis odio odit accusantium neque illo. Magnam nam ex. Qui rerum amet. Temporibus nobis praesentium autem eum omnis consequatur et.\n\nPossimus reiciendis corporis a cupiditate et quibusdam aspernatur sequi iure. Magnam dolores rerum aut eos aut. Veritatis ducimus porro neque id rerum. Laudantium doloremque aut.",
                            IntroductionParagraph = false,
                            Title = "Example Paragraph 6",
                            WikiPageId = 1
                        },
                        new
                        {
                            Id = 7,
                            Content = "Assumenda nulla rem vel quo fuga ratione dolor dolorum. Amet quasi nihil perspiciatis quas voluptas qui commodi quas. Odit odio natus. Voluptatibus dolor dolores quod eos rem harum. Dolor possimus aut eveniet occaecati qui.\n\nIn error officiis iusto ipsum fugiat non autem ratione dignissimos. Voluptas architecto ad sed officia sunt rerum dolore quod. Earum odit nisi. Non fugit aut doloribus dolores dolorem.\n\nSit sed animi aut quisquam voluptatem commodi ipsa et illum. Quam cumque non et ut. Velit sed suscipit debitis quia porro accusantium. Occaecati non dolor porro veritatis nesciunt quia. Quidem natus nam quia voluptate aut ea est at. Doloremque et quis.\n\nDignissimos et minima maiores nihil non ipsa omnis sunt omnis. Temporibus neque laboriosam veniam doloribus quisquam. Et ex et a expedita error dignissimos.\n\nMagnam architecto dolores corrupti. Ipsum assumenda culpa reprehenderit at cumque. Ab voluptas repellendus similique molestias. Sed est praesentium est accusamus commodi. Sit quo ipsa maiores nobis voluptates voluptatem.",
                            IntroductionParagraph = false,
                            Title = "Example Paragraph 7",
                            WikiPageId = 1
                        },
                        new
                        {
                            Id = 8,
                            Content = "Ex consequatur saepe provident cumque ad repellendus fuga non. Blanditiis ut illum aliquam perferendis natus. Aut id eos illo dolorem harum voluptas officiis. Assumenda vel eligendi.\n\nPraesentium voluptates cum et debitis omnis dolor alias distinctio quod. Rem animi eos perferendis quia unde fugiat velit ut nulla. Eligendi est incidunt expedita. Aut commodi repellat laudantium ut.\n\nHic similique et sint fuga. Sequi voluptatibus dolor. Id officiis veritatis ratione vitae dolore sit quibusdam qui rerum. Animi ab ut esse esse corrupti eligendi. Aliquam blanditiis distinctio est eos aut dolore.\n\nDolorem fugiat in voluptate et pariatur laborum. Adipisci deserunt at qui qui blanditiis officiis expedita cumque. Esse beatae molestiae. Omnis modi optio a nihil odio ut ullam nisi vero.\n\nBeatae ea ipsum recusandae animi recusandae. Voluptatem facilis autem similique ut asperiores est. Voluptatem quia autem qui qui voluptatibus ut aut. Omnis doloribus earum fugiat. Voluptatibus quasi consectetur cupiditate maxime consectetur a et.",
                            IntroductionParagraph = false,
                            Title = "Example Paragraph 8",
                            WikiPageId = 2
                        },
                        new
                        {
                            Id = 9,
                            Content = "Veritatis consectetur sit reprehenderit architecto vero. Velit veniam saepe aliquid officia. Error expedita facere.\n\nOmnis voluptatem et nam et qui. Sunt repudiandae sint. Nesciunt consequatur incidunt quas qui aliquid accusantium.\n\nExcepturi omnis ad expedita. Aperiam quia eligendi tenetur dignissimos non eius voluptatibus assumenda ipsa. Vitae occaecati ab eum et quam qui enim adipisci voluptatem. Veniam ut ab.\n\nMagnam possimus nisi ab illo ut ea consequatur dolor. Sapiente expedita voluptate autem. Qui architecto ab voluptas amet fugiat qui aut. Est sint consequatur et ex et eum. Et ut vitae voluptatibus voluptatem rerum nihil.\n\nEius enim reprehenderit iusto sit ut eius qui. In aut quibusdam aliquam. Ratione assumenda fuga. Vel provident doloremque. Repudiandae repellat dolor et necessitatibus quis. Aliquid qui voluptates quaerat aliquid alias fugiat eum maiores.",
                            IntroductionParagraph = false,
                            Title = "Example Paragraph 9",
                            WikiPageId = 1
                        },
                        new
                        {
                            Id = 10,
                            Content = "Repellendus consequuntur animi deleniti voluptate maxime enim asperiores. Voluptatum quo nemo ut cupiditate cum rerum laborum. Officiis odio neque aspernatur officiis natus voluptatem odit assumenda asperiores. Fuga deleniti omnis aut eum velit aspernatur sit.\n\nOdio laboriosam voluptatum fuga numquam asperiores debitis commodi cupiditate. Voluptatum asperiores omnis deleniti dolore aliquam. Deleniti aut enim sit dolorem. Quo qui ipsam.\n\nDolorum et consequatur facere est numquam. Dolores et quia dolores asperiores. Magnam laborum omnis quisquam ut.\n\nDolores ipsa sit est placeat aut beatae ipsam quas quaerat. Cupiditate rerum voluptatum nobis eos minima. Qui aut eum voluptas sed dolorem blanditiis rerum qui.\n\nEt laudantium debitis autem id et. Ipsa illum libero iusto. Porro id quod animi qui. Natus laboriosam corrupti et ut deleniti aut sit. Dolor voluptatum officia alias aut iure qui nulla voluptatem. Et eos inventore et accusamus.",
                            IntroductionParagraph = false,
                            Title = "Example Paragraph 10",
                            WikiPageId = 1
                        });
                });

            modelBuilder.Entity("wiki_backend.Models.StyleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArticleColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArticleRightColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArticleRightInnerColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterListLinkTextColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterListTextColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WikiName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Styles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleColor = "#526cad",
                            ArticleRightColor = "#3c5fb8",
                            ArticleRightInnerColor = "#2b4ea6",
                            BodyColor = "#507ced",
                            FooterListLinkTextColor = "#1d305e",
                            FooterListTextColor = "#233a71",
                            Logo = "/img/logo.png",
                            WikiName = "Your Wiki"
                        });
                });

            modelBuilder.Entity("wiki_backend.Models.WikiPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteSub")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WikiPages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleNote = "Example RoleNote 1",
                            SiteSub = "Example SiteSub 1",
                            Title = "Example Page 1"
                        },
                        new
                        {
                            Id = 2,
                            RoleNote = "Example RoleNote 2",
                            SiteSub = "Example SiteSub 2",
                            Title = "Example Page 2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("wiki_backend.Models.Paragraph", b =>
                {
                    b.HasOne("wiki_backend.Models.WikiPage", "WikiPage")
                        .WithMany("Paragraphs")
                        .HasForeignKey("WikiPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WikiPage");
                });

            modelBuilder.Entity("wiki_backend.Models.WikiPage", b =>
                {
                    b.Navigation("Paragraphs");
                });
#pragma warning restore 612, 618
        }
    }
}
