// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wiki_backend.DatabaseServices;

#nullable disable

namespace wiki_backend.Migrations
{
    [DbContext(typeof(WikiDbContext))]
    [Migration("20240208093925_AddUserSubmittedWikiPage")]
    partial class AddUserSubmittedWikiPage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("wiki_backend.Models.Paragraph", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParagraphImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParagraphImageText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WikiPageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WikiPageId");

                    b.ToTable("Paragraphs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Example content 1",
                            ParagraphImage = "https://html5-templates.com/demo/wikipedia-template/img/pencil.jpg",
                            ParagraphImageText = "Example ParagraphImageText 1",
                            Title = "Example Paragraph 1",
                            WikiPageId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Example content 2",
                            ParagraphImage = "https://html5-templates.com/demo/wikipedia-template/img/pencil.jpg",
                            ParagraphImageText = "<Link to=\"/page/Example%20Page%201\"> This links to Example page 1 </Link>",
                            Title = "Example Paragraph 2",
                            WikiPageId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "Aut animi veritatis alias. Repellat libero officia non magni dolorem esse doloremque aspernatur. Nemo recusandae sit alias minima.\n\nNulla optio nihil iste aut eveniet et ipsa. Aliquam et quia nobis vitae. Velit nihil doloremque ducimus blanditiis et repellendus voluptates consequatur. Quae sit non sed aut aliquid. Perspiciatis nostrum maxime cupiditate tempore est fugit minima possimus. Rem et corrupti vitae eum in voluptatem non perferendis.\n\nAut soluta nihil maiores incidunt suscipit. Voluptatum vel iure corrupti quas. Voluptatem quae suscipit similique enim officiis quos. Neque doloribus eos explicabo adipisci repellat odio fugiat veritatis molestias. Facere laudantium consequatur dignissimos exercitationem blanditiis necessitatibus.\n\nAut illum est voluptatem enim magnam. Suscipit iure et reprehenderit saepe nemo dolorem voluptas dolorum. Voluptas molestias temporibus provident. Voluptatem suscipit at et.\n\nSit ex aut porro tempore iure esse quisquam. Praesentium occaecati fuga numquam sequi qui est quis alias. Voluptates rerum consequatur reiciendis unde molestias est a ipsam.",
                            Title = "Example Paragraph 3",
                            WikiPageId = 1
                        },
                        new
                        {
                            Id = 4,
                            Content = "Nihil magnam quas aut quibusdam cumque voluptatem est deleniti. Ex quod facere voluptatem. Non autem et vero cumque.\n\nNihil nihil quia dolor perferendis neque nesciunt. Aliquam aut eum ad. Quod aliquam occaecati qui illum. Maiores officia molestiae nulla omnis aspernatur voluptas dolor. Delectus eius sint laudantium est voluptatibus dolor.\n\nDeserunt veritatis aut. Assumenda labore alias quae quasi. Dolor molestiae deserunt totam tempore illo deserunt quis iure exercitationem. Aut maiores aut quos laborum est. Quibusdam quisquam perspiciatis dolor veniam earum quisquam alias doloremque ex. Minus est eos voluptas exercitationem quia occaecati voluptas natus.\n\nMagnam ut iusto quod enim blanditiis consequatur non corporis rerum. Sed rerum veritatis ullam velit veritatis non. Adipisci qui excepturi sint recusandae voluptatibus dolores repudiandae doloribus sapiente. Reiciendis reiciendis minus sed voluptatem voluptatem repellat nobis et maiores. Iure eaque doloremque consequuntur delectus vel aut.\n\nQuaerat similique quam impedit ut. Accusantium assumenda odio ducimus vel delectus maiores. Tenetur iusto nihil illo assumenda adipisci.",
                            Title = "Example Paragraph 4",
                            WikiPageId = 2
                        },
                        new
                        {
                            Id = 5,
                            Content = "Est dolores officiis voluptatibus officia quo. Sed iste maiores eveniet voluptatum similique in sed. Aspernatur occaecati placeat rerum perspiciatis ut laboriosam vel et. Accusantium ut odio et explicabo eos sit aut minus perspiciatis. Ea ea exercitationem eaque non enim. Consequuntur consequatur earum accusamus.\n\nNulla quos velit ab quibusdam aut assumenda autem. Reprehenderit culpa sint et autem voluptas expedita similique doloremque qui. Et quos excepturi pariatur possimus. In quibusdam non accusantium harum voluptatem voluptatem. Magni culpa sed nihil. Quisquam suscipit consequatur nemo reprehenderit placeat assumenda iusto.\n\nQui labore suscipit eos rerum et quisquam. Eos impedit tempore voluptatibus incidunt voluptatum dolorum ut dolor molestiae. Consectetur ratione consequatur.\n\nConsequatur necessitatibus suscipit alias. Quia vel qui quia vitae qui placeat voluptas omnis. Excepturi sed libero rem.\n\nCumque sunt quia dolor rem architecto quis dolores nihil officia. Dicta odio corporis voluptatibus exercitationem asperiores. Numquam est modi natus eius id officia officia.",
                            Title = "Example Paragraph 5",
                            WikiPageId = 2
                        },
                        new
                        {
                            Id = 6,
                            Content = "Dolor iusto illum inventore ut nisi perspiciatis. Accusantium cupiditate expedita. Modi vel aliquam. Quo quaerat aut ea et vitae quo voluptatibus atque nulla. Qui itaque asperiores earum dolor incidunt sunt rem.\n\nFugit sit ut harum reiciendis ullam. Aut in velit. Numquam quis maxime necessitatibus temporibus ex ullam atque. Deserunt sunt sint.\n\nEa quidem facere et voluptates voluptates veniam totam doloribus. Ut vero eum id labore libero provident. Quis sunt dolorem qui autem eaque. Iste hic molestiae consequuntur sed ea quia ut adipisci architecto. Praesentium qui vitae architecto qui inventore.\n\nCumque temporibus pariatur voluptatum totam quod. Dolorem animi dolor iste. Quaerat aut quia nisi quia est dicta. Ullam reprehenderit sed mollitia dolore beatae. Fugit dolorem rem aperiam expedita delectus illo doloribus dolor velit.\n\nId perferendis maiores. Nihil dolorum sed voluptatem odit. Est debitis tempora consequatur et velit eos ut quae qui. Doloribus voluptas et laborum deserunt dolor totam eveniet.",
                            Title = "Example Paragraph 6",
                            WikiPageId = 1
                        },
                        new
                        {
                            Id = 7,
                            Content = "Nostrum dolore error. Deserunt numquam maxime fuga. Id distinctio error facere natus voluptas et. Quidem dolorem labore occaecati qui reprehenderit esse repellat facilis.\n\nAlias consectetur doloribus quia voluptatum et laudantium. Provident non voluptatem amet. Dolores deserunt doloribus facere veniam ut. Autem impedit laudantium nihil adipisci et est cupiditate et soluta.\n\nEt voluptates alias nobis adipisci. Odio nam dolor eos libero facere sint quia nesciunt. Ut earum similique architecto magni. Deserunt ab soluta perspiciatis. Voluptas molestiae eum laboriosam.\n\nVoluptatibus quia laboriosam. Totam velit voluptatibus et sapiente accusamus tempora laudantium eligendi. Nihil numquam aut odio quia est animi. Cumque et rem quas corrupti temporibus asperiores eum incidunt unde. Ipsam cupiditate voluptas iusto error. Sit quos fugit tempora vero sint ipsam exercitationem.\n\nInventore quod vero quas. Voluptas hic enim accusantium assumenda nihil. Explicabo sapiente officiis architecto soluta ab repellendus consequuntur.",
                            Title = "Example Paragraph 7",
                            WikiPageId = 1
                        },
                        new
                        {
                            Id = 8,
                            Content = "Consectetur quisquam a mollitia porro. Qui doloribus ea omnis. Est omnis dolore perferendis excepturi culpa esse. Ducimus nulla cum vel explicabo ex alias eligendi. Vitae fuga eos alias non architecto et.\n\nIpsa aut sunt eveniet voluptas. Ratione minus non facere eum quia voluptatum totam omnis. Odio aliquam ut earum omnis voluptas placeat. Ipsam rerum architecto qui deleniti autem eos omnis.\n\nExercitationem voluptatem incidunt qui et est. Quia vel assumenda tenetur inventore. Dicta debitis omnis saepe. Sint est possimus eum iure accusamus aliquid dolores. Est et sed dolores omnis eaque cupiditate nam esse. In molestias velit voluptatem voluptas recusandae et non.\n\nReprehenderit eos aperiam adipisci totam. Ut voluptatem officia similique sint. Est omnis molestiae ut rerum aut deserunt maiores. Voluptates est ut corporis recusandae consequatur dolores culpa. Consequatur provident dolor autem nam aut dolorum quia id ut.\n\nPossimus voluptatum ut cumque. Exercitationem id natus. Consequatur quia impedit earum fuga. Neque vero minus deleniti. Eius molestiae illum numquam nobis minima ut sint quaerat esse. Voluptatem libero enim unde explicabo voluptatibus architecto sed.",
                            Title = "Example Paragraph 8",
                            WikiPageId = 1
                        },
                        new
                        {
                            Id = 9,
                            Content = "Eos ea natus aut dignissimos omnis magnam porro numquam. Amet dignissimos soluta quo voluptas enim exercitationem omnis possimus voluptas. Qui explicabo laboriosam consequatur recusandae.\n\nLaudantium repudiandae eos. Illum dolorem ullam minus dignissimos magni ut blanditiis. Dolore dolores explicabo quaerat mollitia voluptas alias neque. Vitae sed quo eligendi nihil repellat et. Tenetur ipsam dolores aut voluptatem id deleniti eligendi voluptate sit.\n\nQuaerat et voluptatem. Incidunt aut esse ut ducimus consequatur quis neque molestiae iusto. Rerum qui impedit modi inventore. Animi cumque a vel voluptatum.\n\nAsperiores unde eaque autem corrupti tempore omnis. Voluptatibus adipisci sit voluptatibus aut praesentium fuga ut debitis et. Nisi suscipit ducimus quae consequatur voluptas vel.\n\nEos voluptatum at velit consequatur. Totam est nihil voluptas quo qui unde. Non nulla quibusdam facere iure aut.",
                            Title = "Example Paragraph 9",
                            WikiPageId = 1
                        },
                        new
                        {
                            Id = 10,
                            Content = "Vitae quia consectetur officiis dolorem magni in. Consequatur officiis magni quisquam tenetur corporis et minima. Enim assumenda dolores eum veniam et vitae rerum. Placeat tempore fugit ut ex. Delectus consequuntur deleniti impedit autem nobis non. Iste natus incidunt tempora dignissimos.\n\nQuia voluptatem soluta. Nemo reprehenderit ex deserunt voluptatem et quis. Perferendis nihil ratione. Enim provident non laboriosam id. Et sunt quam natus quia.\n\nLaudantium amet ipsam nostrum quis. Repellendus doloribus nesciunt culpa odit ut est. Veritatis reiciendis qui rem ratione sed qui aut eum. Blanditiis labore asperiores sunt. Consectetur qui enim ea.\n\nDolorem atque est quod quidem quis est. Aspernatur consequatur voluptas eligendi dolorem debitis harum. Et dolore id. Consequatur repellendus commodi consequatur dolorem architecto. Sunt sapiente deleniti praesentium impedit aut qui omnis sunt.\n\nAccusantium non placeat. Reiciendis esse fugit laudantium eum eos ut aperiam. Rerum mollitia voluptas ut doloribus qui hic.",
                            Title = "Example Paragraph 10",
                            WikiPageId = 2
                        },
                        new
                        {
                            Id = 11,
                            Content = "Blanditiis consequuntur id ut sit quae. Et illum voluptatem fuga omnis facere molestiae sequi. Vero deleniti sequi quae error et. Ab laboriosam et.\n\nConsequatur amet officiis quibusdam nemo quo ipsam nam assumenda. Optio in qui. Quisquam a doloremque et. Quia odio et tempora ea ipsum. Soluta laboriosam expedita magni eum ex delectus.\n\nEos ullam totam qui commodi omnis. Earum a sit molestias sunt. Quia minus illo ipsum quia quo voluptatem voluptatem aliquam ut. Tenetur consequatur eligendi est magnam voluptatem amet eaque officia voluptatem. Harum vero aut vel aut veniam accusamus. Qui corporis molestias ut mollitia reprehenderit libero suscipit omnis et.\n\nEarum soluta esse vel et exercitationem. Ea quo facilis sit explicabo exercitationem occaecati non consequatur quidem. Aut sunt autem molestiae architecto molestias at temporibus fugiat.\n\nItaque qui maxime nihil. Qui alias odit aut officia et laboriosam laudantium. Earum et corporis quo rerum tenetur qui ipsam ea ipsum. Excepturi quam ipsa eaque quod dolores est. Earum eum modi tempora a sunt sunt sequi aut repellat. Accusantium sed at et repudiandae harum.",
                            Title = "Example Paragraph 11",
                            WikiPageId = 2
                        },
                        new
                        {
                            Id = 12,
                            Content = "Facilis aliquid qui error animi ut iusto. Libero architecto iste consequatur dignissimos est. Culpa doloremque numquam totam aperiam dolorum facilis iure. Consectetur mollitia vel quas quis id tenetur. Sed enim praesentium sint quia id molestiae vero ut. Eveniet labore voluptatem voluptatum cum ab quibusdam dicta voluptas.\n\nSed sequi eum est. Ab eveniet labore neque. Velit sit consectetur dolores consequatur aspernatur. Porro rem et minima accusantium animi cupiditate laborum. Commodi ut voluptate reiciendis quasi ducimus aut voluptas. Et autem eius odio quas et odit.\n\nUt vel beatae aliquid. Vel sed dolores rerum et commodi. Autem necessitatibus eum nulla modi error veniam rem qui.\n\nQuo rem enim magni. Assumenda porro ratione deserunt ut tenetur provident qui. Rem tempora fugit reiciendis sed exercitationem temporibus similique nostrum qui. Perspiciatis molestiae molestiae excepturi perferendis.\n\nSed eligendi impedit dolor est neque. Veniam quos sit et odit in ut. In excepturi inventore ut esse. Reiciendis quis est molestiae pariatur inventore voluptatem.",
                            Title = "Example Paragraph 12",
                            WikiPageId = 1
                        },
                        new
                        {
                            Id = 13,
                            Content = "Alias cum reprehenderit ut voluptatum. Quo unde autem asperiores ut. Ipsum doloribus eveniet. Pariatur iusto nisi. Facilis consequatur optio debitis sed qui modi saepe cum exercitationem. Fugiat praesentium ipsam rerum.\n\nAb ad quo praesentium ut doloremque. Omnis velit harum ad consequatur non temporibus sed. Perferendis natus nostrum quos ut ratione tenetur voluptatibus totam. Vel assumenda necessitatibus excepturi delectus deleniti excepturi maxime ipsum culpa. In est dolore est doloremque.\n\nEt ut libero ducimus aut id culpa voluptas. Doloremque nisi qui sed. Aperiam qui facilis quod eaque omnis tenetur ducimus atque est. Voluptatem harum qui maiores qui aut eos. Non culpa tenetur magnam laborum reprehenderit. Sit eaque expedita voluptatem sed fuga et architecto sit esse.\n\nSapiente omnis hic autem magni eos. Fuga deserunt et inventore voluptatem accusantium est itaque. Fugiat cupiditate enim molestias pariatur accusamus. Et provident molestias aut odio ut impedit ipsum modi.\n\nAccusamus aut hic aperiam sunt nisi officiis atque aliquid. Eos hic aut sapiente non alias. Omnis modi et consequatur qui molestiae earum perferendis eum. Expedita velit ut minus tenetur et. Quod eaque voluptatem quibusdam labore nihil.",
                            Title = "Example Paragraph 13",
                            WikiPageId = 1
                        },
                        new
                        {
                            Id = 14,
                            Content = "Ut quae quis. Est occaecati asperiores ut. Et exercitationem quod quibusdam quo et. Maxime libero expedita vitae quis consequatur delectus. Est nihil doloremque molestias.\n\nBeatae quod odio omnis repellat vero ex veritatis. Enim placeat porro odio sit velit laudantium mollitia magnam optio. Dolorum dicta nihil quis dolor. Ea aliquid aut nihil. Ipsa fugiat perferendis et dolores nihil.\n\nMaxime quis animi et ut assumenda eum repellat a. Magnam eaque maxime enim exercitationem. Non rerum pariatur. Reprehenderit sequi autem fuga ut ab autem et officiis earum. Voluptas nihil sed sed laboriosam. Commodi aut ullam aut magni distinctio vel adipisci.\n\nSed minima tenetur dolorum numquam numquam. Sint hic voluptatum vitae. Sapiente dolorem tenetur autem assumenda maiores officia dignissimos vel labore.\n\nQui molestiae quaerat quo aspernatur iste. Natus maiores consequuntur quia laborum ad corrupti maxime sunt. Adipisci sunt facilis exercitationem sed autem.",
                            Title = "Example Paragraph 14",
                            WikiPageId = 2
                        },
                        new
                        {
                            Id = 15,
                            Content = "Ut et nisi sed labore dolore non rerum aut tempora. Itaque autem non est fuga quibusdam quasi voluptate est ut. Vel qui omnis aut consectetur earum quos dolorem saepe. Nobis blanditiis sapiente culpa laboriosam voluptatem eos eveniet. Repellendus numquam consequatur et deleniti. Veniam veritatis quo molestiae aut.\n\nEligendi cum non quaerat architecto et dolorem qui nihil et. Dolore ea asperiores. Et enim aperiam eum molestias atque molestias. Doloribus neque possimus fugiat ut non.\n\nNihil rem quia cumque. Odit cumque sapiente odio delectus eum eveniet repellendus. Sunt dolore sint est.\n\nDistinctio dolores laborum et. Soluta molestiae voluptate eos adipisci. Maxime consectetur minima optio culpa repudiandae et voluptatem. Sapiente ipsum culpa amet voluptas doloremque similique vel nihil. Inventore est quaerat non nam voluptatem quo qui maiores quis. Eum pariatur eum natus atque enim saepe.\n\nOmnis porro sapiente blanditiis dolor adipisci et voluptatem ad. Et in voluptates voluptas et asperiores quia quod ut nesciunt. Ut laboriosam odio voluptas enim omnis sed possimus. Aut reiciendis sunt qui. Sint voluptate ex quaerat molestiae et.",
                            Title = "Example Paragraph 15",
                            WikiPageId = 1
                        },
                        new
                        {
                            Id = 16,
                            Content = "Porro praesentium dolorem alias. Fuga magni beatae dolor. Fugiat expedita facilis sed magnam. Et nobis molestias at assumenda.\n\nMinima omnis odit id modi dolorem ut voluptatem. Debitis ullam saepe consequatur officiis porro deleniti. Repudiandae ducimus qui ullam voluptas quo veritatis et perspiciatis ad.\n\nPerspiciatis quia laboriosam enim possimus sit non aut nihil adipisci. Iste quia occaecati voluptas porro magni eos id aspernatur aut. Temporibus est velit laborum explicabo expedita ea quos et. Molestias dolor est fugiat.\n\nSequi doloremque fugiat deserunt sequi voluptas quia repellat. Id iste totam suscipit in. Voluptates perferendis ad. Eum qui saepe aliquid possimus sit et.\n\nVeniam maxime et quas nihil placeat. Aut voluptatem reiciendis maiores odit corporis. Est quidem minima. Perspiciatis hic rerum. Dolorum quasi eligendi soluta. Itaque aliquid voluptas.",
                            Title = "Example Paragraph 16",
                            WikiPageId = 1
                        },
                        new
                        {
                            Id = 17,
                            Content = "Illo libero quibusdam necessitatibus. Ullam ad ut. A rerum enim sint quasi aliquam autem ducimus harum. Dolores aut corporis vero magnam illo corporis quia est inventore. Id quia sed reiciendis at consectetur molestiae eligendi adipisci suscipit.\n\nVelit at ullam et. Numquam architecto temporibus consequuntur quod facilis quos eaque occaecati. Delectus nihil alias quia quas vel inventore iusto. Sed necessitatibus sequi aut labore aut doloribus eligendi.\n\nSed rerum et est non sit. Ipsum ab velit. Quidem sed ipsa dolores ut nemo totam. Rerum reprehenderit cum sequi nulla. Suscipit omnis ipsa temporibus doloremque consequatur asperiores. Odio molestias sunt quod.\n\nVel nulla et ab laudantium consequuntur odio. Placeat qui totam. Tempora et omnis natus eum qui sapiente rerum facilis. Natus quas minima quas itaque voluptatum.\n\nSit nihil quia maxime perspiciatis eum ea quibusdam aut hic. Occaecati quo nihil tempora. Eligendi accusamus impedit eos. Nulla quia ea.",
                            Title = "Example Paragraph 17",
                            WikiPageId = 2
                        });
                });

            modelBuilder.Entity("wiki_backend.Models.StyleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArticleColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArticleRightColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArticleRightInnerColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BodyColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterListLinkTextColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FooterListTextColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WikiName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Styles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleColor = "#526cad",
                            ArticleRightColor = "#3c5fb8",
                            ArticleRightInnerColor = "#2b4ea6",
                            BodyColor = "#507ced",
                            FooterListLinkTextColor = "#1d305e",
                            FooterListTextColor = "#233a71",
                            Logo = "/img/logo.png",
                            WikiName = "Your Wiki"
                        });
                });

            modelBuilder.Entity("wiki_backend.Models.WikiPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteSub")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WikiPages");

                    b.HasDiscriminator<string>("Discriminator").HasValue("WikiPage");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleNote = "Example RoleNote 1",
                            SiteSub = "Example SiteSub 1",
                            Title = "Example Page 1"
                        },
                        new
                        {
                            Id = 2,
                            RoleNote = "Example RoleNote 2",
                            SiteSub = "Example SiteSub 2",
                            Title = "Example Page 2"
                        });
                });

            modelBuilder.Entity("wiki_backend.Models.UserSubmittedWikiPage", b =>
                {
                    b.HasBaseType("wiki_backend.Models.WikiPage");

                    b.Property<bool>("Approved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNewPage")
                        .HasColumnType("bit");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("WikiPageId")
                        .HasColumnType("int");

                    b.HasIndex("WikiPageId");

                    b.HasDiscriminator().HasValue("UserSubmittedWikiPage");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("wiki_backend.Models.Paragraph", b =>
                {
                    b.HasOne("wiki_backend.Models.WikiPage", "WikiPage")
                        .WithMany("Paragraphs")
                        .HasForeignKey("WikiPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WikiPage");
                });

            modelBuilder.Entity("wiki_backend.Models.UserSubmittedWikiPage", b =>
                {
                    b.HasOne("wiki_backend.Models.WikiPage", "WikiPage")
                        .WithMany()
                        .HasForeignKey("WikiPageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("WikiPage");
                });

            modelBuilder.Entity("wiki_backend.Models.WikiPage", b =>
                {
                    b.Navigation("Paragraphs");
                });
#pragma warning restore 612, 618
        }
    }
}
