version: '3.8'

services:
  wiki-backend:
    image: your-wiki-backend-image:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"  # Adjust the port mapping as needed
    depends_on:
      - sql-server

  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: YourPassword123!  # Change this to a secure password
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"  # Adjust the port mapping as needed