version: '3.8'

services:
  wiki-backend:
    image: wiki-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${PICTURES_PATH}:/pictures
    ports:
      - "5000:80"  # Adjust the port mapping as needed
    depends_on:
      - sql-server
    entrypoint: ["bash", "/wait-for-it.sh", "sql-server:1433", "-t", "120", "--", "dotnet", "wiki-backend.dll"] #Uncomment this if your PC is too slow to start the DB before the backend tries to access it, don't forget dockerfile
    environment:
      ASPNETCORE_CONNECTIONSTRING: ${ASPNETCORE_CONNECTIONSTRING}
      ADMINUSER_EMAIL: ${ADMINUSER_EMAIL}
      ADMINUSER_PASSWORD: ${ADMINUSER_PASSWORD}
      ADMINUSER_USERNAME: ${ADMINUSER_USERNAME}
      TESTUSER_EMAIL: ${TESTUSER_EMAIL}
      TESTUSER_PASSWORD: ${TESTUSER_PASSWORD}
      TESTUSER_USERNAME: ${TESTUSER_USERNAME}
      JWT_ISSUER_SIGNING_KEY: ${JWT_ISSUER_SIGNING_KEY}
      JWT_VALID_AUDIENCE: ${JWT_VALID_AUDIENCE}
      JWT_VALID_ISSUER: ${JWT_VALID_ISSUER}
      JWT_TOKEN_TIME: ${JWT_TOKEN_TIME}
      PICTURES_PATH: ${PROFILE_PICTURES_PATH}
      PICTURES_PATH_CONTAINER: ${PICTURES_PATH_CONTAINER}

  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: ${DB_PASSWORD} 
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"  # Adjust the port mapping as needed