const purgecss = require('@fullhuman/postcss-purgecss');

module.exports = {
  plugins: [
    ...(process.env.NODE_ENV === 'production'
      ? [
          purgecss({
            content: ['./src/**/*.{tsx,ts,jsx,js}', './index.html'],
            keyframes: true,
            fontFace: true,
            variables: true,
            safelist: {
              standard: [
                /^era-/,
                /^glass-/,
                /^frutiger-/,
                /^ql-/,
                /^flag-badge$/,
                /^depth-\d+$/,
                /^fp-/,
              ],
              deep: [
                /^wikipage-/,
                /^hamburger-/,
                /^profile-/,
                /^category-/,
                /^forum-/,
                /^moderation-/,
                /^article-/,
                /^sidebar/,
                /^top-header/,
                /^headerLinks/,
                /^logo-container/,
                /^page-title/,
                /^title-container/,
                /^mainsection/,
                /^pagefooter/,
                /^footerlinks/,
                /^wrapAll/,
                /^clearfix/,
                /^editButton/,
                /^site-logo/,
                /^paragraph-image/,
                /^logout-button/,
                /^era-button/,
                /^aero-/,
                /^lgb-/,
                /^preset-/,
              ],
              greedy: [
                /^btn/,
                /^form-/,
                /^modal/,
                /^dropdown/,
                /^alert/,
                /^input-group/,
                /^table/,
                /^card/,
                /^badge/,
                /^list-group/,
                /^spinner-/,
                /^toast/,
                /^tooltip/,
                /^popover/,
                /^offcanvas/,
                /^pagination/,
                /^carousel/,
                /^accordion/,
                /^breadcrumb/,
                /^progress/,
                /^navbar/,
                /^close/,
                /^nav/,
                /^tab-/,
              ],
            },
            blocklist: [],
          }),
        ]
      : []),
  ],
};
