name: Backend Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: wiki-backend 

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0'

    - name: Restore dependencies
      run: dotnet restore ../../wiki-backend/wiki-backend/wiki-backend.csproj

    - name: Build
      run: dotnet build --configuration Release

    - name: Run unit tests
      run: dotnet test ../../wiki-backend/UnitTests/UnitTests.csproj --configuration Release

    - name: Run integration tests
      run: dotnet test ../../wiki-backend/IntegrationTests/IntegrationTests.csproj --configuration Release
