name: Backend Tests

on:
  push:
  pull_request:
    branches:
      - '**'
    paths:
      - '**.cs'
      - '**.csproj'

jobs:
  tests:
    runs-on: ubuntu-latest
    env: 
      INTEGRATIONTEST_CONNECTIONSTRING: ${{ secrets.INTEGRATIONTEST_CONNECTIONSTRING }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0'

    - name: Restore dependencies
      run: dotnet restore ./wiki-backend/wiki-backend/wiki-backend.csproj 

    - name: Build
      run: dotnet build ./wiki-backend/wiki-backend/wiki-backend.csproj --configuration Release

    - name: Run unit tests
      run: dotnet test ./wiki-backend/UnitTests/UnitTests.csproj --configuration Release

    - name: Start SQL Server container
      run: |
        docker run -d --name sql-server -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=${{ secrets.DB_PASSWORD }}" -p 1433:1433 mcr.microsoft.com/mssql/server:latest

    - name: Wait for SQL Server to be ready
      run: dockerize -wait tcp://localhost:1433 -timeout 1m

    - name: Run integration tests
      run: dotnet test ./wiki-backend/IntegrationTests/IntegrationTests.csproj --configuration Release
