name: Build and Deploy Docker Compose

on:
  push:
    branches:
      - main
      - '**'

jobs:  
  build:
    runs-on: ubuntu-latest
    env:
      PICTURES_PATH: ${{ secrets.PICTURES_PATH }}
      ASPNETCORE_CONNECTIONSTRING: ${{ secrets.ASPNETCORE_CONNECTIONSTRING }}
      INTEGRATIONTEST_CONNECTIONSTRING: ${{ secrets.INTEGRATIONTEST_CONNECTIONSTRING }}
      ADMINUSER_EMAIL: ${{ secrets.ADMINUSER_EMAIL }}
      ADMINUSER_PASSWORD: ${{ secrets.ADMINUSER_PASSWORD }}
      ADMINUSER_USERNAME: ${{ secrets.ADMINUSER_USERNAME }}
      TESTUSER_EMAIL: ${{ secrets.TESTUSER_EMAIL }}
      TESTUSER_PASSWORD: ${{ secrets.TESTUSER_PASSWORD }}
      TESTUSER_USERNAME: ${{ secrets.TESTUSER_USERNAME }}
      JWT_ISSUER_SIGNING_KEY: ${{ secrets.JWT_ISSUER_SIGNING_KEY }}
      JWT_VALID_AUDIENCE: ${{ secrets.JWT_VALID_AUDIENCE }}
      JWT_VALID_ISSUER: ${{ secrets.JWT_VALID_ISSUER }}
      JWT_TOKEN_TIME: ${{ secrets.JWT_TOKEN_TIME }}
      REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      PROFILE_PICTURES_PATH: ${{ secrets.PROFILE_PICTURES_PATH }}
      PICTURES_PATH_CONTAINER: ${{ secrets.PICTURES_PATH_CONTAINER }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push wiki-backend Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/wiki-backend ./wiki-backend/wiki-backend
        docker push ${{ secrets.DOCKER_USERNAME }}/wiki-backend

    - name: Build and push wiki-frontend Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/wiki-frontend ./wiki-frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/wiki-frontend

    - name: Deploy
      run: |
        docker-compose -f docker-compose.yml up -d